[tool_alias]
pbkit = "asdf:pbkit/asdf-pbkit"

[tools]
deno = "2.6.10"
java = "temurin-25.0.2"
python = "3.14.3"
terraform = "1.14.5"
node = "25.6.1"
go = "1.26.0"
pbkit = "0.0.72"
zig = "0.15.2"
bun = "1.3.9"
hermes = "0.13.0"
binaryen = "126"
opencode = "1.2.10"
"npm:@sourcegraph/amp" = "0.0.1771812469-gd3302f"
"npm:@openai/codex" = "0.104.0"
"npm:opencode-supermemory" = "2.0.2"

[settings]
asdf_compat = true
idiomatic_version_file_enable_tools = ["python"]
