[tool_alias]
pbkit = "asdf:pbkit/asdf-pbkit"

[tools]
deno = "2.6.10"
java = "temurin-25.0.2"
python = "3.14.3"
terraform = "1.14.6"
node = "25.7.0"
go = "1.26.0"
pbkit = "0.0.72"
zig = "0.15.2"
bun = "1.3.9"
hermes = "0.13.0"
binaryen = "126"
opencode = "1.2.13"
"npm:@sourcegraph/amp" = "0.0.1772036468-gdc13c5"
"npm:@openai/codex" = "0.105.0"
"npm:command-code" = "0.17.6"

[settings]
asdf_compat = true
idiomatic_version_file_enable_tools = ["python"]
