[alias]
pbkit = "asdf:pbkit/asdf-pbkit"

[tools]
deno = "2.6.3"
java = "temurin-25.0.0"
python = "3.14.2"
terraform = "1.14.3"
node = "25.2.1"
go = "1.25.5"
pbkit = "0.0.72"
zig = "0.15.2"
bun = "1.3.5"
hermes = "0.13.0"
binaryen = "125"
"npm:@anthropic-ai/claude-code" = "2.0.76"
"npm:ccusage" = "17.2.0"
"npm:@sourcegraph/amp" = "0.0.1766577683-g66e5b8"
"npm:@openai/codex" = "0.77.0"

[settings]
asdf_compat = true
idiomatic_version_file_enable_tools = ["python"]
