[tool_alias]
pbkit = "asdf:pbkit/asdf-pbkit"

[tools]
deno = "2.6.6"
java = "temurin-25.0.1"
python = "3.14.2"
terraform = "1.14.3"
node = "25.5.0"
go = "1.25.6"
pbkit = "0.0.72"
zig = "0.15.2"
bun = "1.3.6"
hermes = "0.13.0"
binaryen = "125"
opencode = "1.1.39"
"npm:@anthropic-ai/claude-code" = "2.1.20"
"npm:ccusage" = "18.0.5"
"npm:@sourcegraph/amp" = "0.0.1769492758-gb98cad"
"npm:@openai/codex" = "0.91.0"
"npm:opencode-supermemory" = "0.1.8"

[settings]
asdf_compat = true
idiomatic_version_file_enable_tools = ["python"]
