[tool_alias]
pbkit = "asdf:pbkit/asdf-pbkit"

[tools]
deno = "2.6.8"
java = "temurin-25.0.2"
python = "3.14.3"
terraform = "1.14.4"
node = "25.6.0"
go = "1.25.7"
pbkit = "0.0.72"
zig = "0.15.2"
bun = "1.3.8"
hermes = "0.13.0"
binaryen = "125"
opencode = "1.1.52"
"npm:@sourcegraph/amp" = "0.0.1770321907-gbab39e"
"npm:@openai/codex" = "0.98.0"
"npm:opencode-supermemory" = "2.0.1"

[settings]
asdf_compat = true
idiomatic_version_file_enable_tools = ["python"]
