[alias]
pbkit = "asdf:pbkit/asdf-pbkit"

[tools]
deno = "2.5.6"
java = "temurin-25.0.0"
python = "3.14.2"
terraform = "1.14.1"
node = "25.2.1"
go = "1.25.5"
pbkit = "0.0.72"
zig = "0.15.2"
bun = "1.3.4"
hermes = "0.13.0"
binaryen = "125"
"npm:@anthropic-ai/claude-code" = "2.0.62"
"npm:ccusage" = "17.1.8"
"npm:@sourcegraph/amp" = "0.0.1765296079-gee64bc"
"npm:@openai/codex" = "0.66.0"
"npm:@google/gemini-cli" = "0.19.4"

[settings]
asdf_compat = true
idiomatic_version_file_enable_tools = ["python"]
